import { useMemo, useState } from 'react'
import { Check, Minus, Plus, Shirt, Sparkles, Trash2, Umbrella } from 'lucide-react'
import type { PackingItem } from '../../types'
import { Button } from '../../components/ui/Button'

export function PackingList({ initial }: { initial: PackingItem[] }) {
  const [items, setItems] = useState(initial)
  const [newItem, setNewItem] = useState('')
  const packed = items.filter(i => i.packed).length; const percent = items.length ? Math.round(packed / items.length * 100) : 0
  const categories = useMemo(() => [...new Set(items.map(i => i.category))], [items])
  const toggle = (id: string) => setItems(v => v.map(i => i.id === id ? { ...i, packed: !i.packed } : i))
  const quantity = (id: string, d: number) => setItems(v => v.map(i => i.id === id ? { ...i, quantity: Math.max(1, i.quantity + d) } : i))
  const add = () => { if (!newItem.trim()) return; setItems(v => [...v, { id: crypto.randomUUID(), name: newItem.trim(), quantity: 1, packed: false, category: 'My extras' }]); setNewItem('') }
  return <section id="packing" className="scroll-mt-24 rounded-2xl border border-black/8 bg-white p-5 md:p-7">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Weather-ready</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Smart packing list</h2><p className="mt-2 flex items-center gap-2 text-sm text-slate"><Sparkles size={14} className="text-amber" />Personalized for conditions and activities</p></div><div className="min-w-[150px] rounded-xl bg-[#f3f1e9] p-3"><div className="flex items-end justify-between"><span className="text-[10px] font-bold uppercase tracking-[.13em] text-slate">Packed</span><strong className="text-lg">{packed} / {items.length}</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-black/10"><span className="block h-full rounded-full bg-forest transition-all" style={{ width: `${percent}%` }} /></div><span className="mt-1 block text-right text-[10px] text-slate">{percent}% complete</span></div></div>
    <div className="mt-6 grid gap-7 md:grid-cols-2">{categories.map(category => <div key={category}><h3 className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-slate">{category.toLowerCase().includes('weather') ? <Umbrella size={14} /> : <Shirt size={14} />}{category}</h3><div className="space-y-1">{items.filter(i => i.category === category).map(item => <div key={item.id} className="packing-item group flex items-center gap-3 rounded-lg px-2 py-2 hover:bg-[#f7f5ee]"><button onClick={() => toggle(item.id)} aria-label={`Mark ${item.name} ${item.packed ? 'unpacked' : 'packed'}`} className={`grid h-5 w-5 place-items-center rounded border ${item.packed ? 'border-forest bg-forest text-white' : 'border-black/20'}`}>{item.packed && <Check size={13} />}</button><span className={`min-w-0 flex-1 text-sm ${item.packed ? 'text-slate line-through' : 'font-medium'}`}>{item.name}{item.reason && <span className="block truncate text-[10px] font-normal text-slate no-underline">{item.reason}</span>}</span><span className="packing-quantity flex items-center rounded-md border border-black/8 opacity-70 group-hover:opacity-100"><button onClick={() => quantity(item.id, -1)} className="p-1" aria-label="Decrease quantity"><Minus size={11} /></button><span className="w-5 text-center text-[11px]">{item.quantity}</span><button onClick={() => quantity(item.id, 1)} className="p-1" aria-label="Increase quantity"><Plus size={11} /></button></span><button onClick={() => setItems(v => v.filter(i => i.id !== item.id))} className="text-slate opacity-0 hover:text-red-600 group-hover:opacity-100" aria-label={`Remove ${item.name}`}><Trash2 size={14} /></button></div>)}</div></div>)}</div>
    <div className="mt-6 flex gap-2 border-t border-black/8 pt-5"><input value={newItem} onChange={e => setNewItem(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()} placeholder="Add your own item" className="h-10 min-w-0 flex-1 rounded-lg border border-black/10 bg-[#f8f7f2] px-3 text-sm outline-none focus:border-forest" /><Button size="sm" variant="secondary" onClick={add}><Plus size={15} /> Add</Button></div>
  </section>
}
