import { useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { ArrowRight, CloudRain, Copy, GripVertical, Plus, Sparkles, Trash2 } from 'lucide-react'
import type { TripAnalysis } from '../../types'
import { Button } from '../../components/ui/Button'
import { api } from '../../services/api'

export function ItineraryBuilder({ tripId, initial }: { tripId: string; initial: TripAnalysis['itinerary'] }) {
  const [days, setDays] = useState(initial); const [selected, setSelected] = useState(0); const [dragged, setDragged] = useState<number | null>(null); const [adding, setAdding] = useState(false); const [title, setTitle] = useState(''); const [time, setTime] = useState('14:00')
  const optimize = useMutation({ mutationFn: () => api.optimizeDay(tripId), onSuccess: data => setDays(data.itinerary) })
  const items = days[selected]?.items || []
  const move = (to: number) => { if (dragged === null || dragged === to) return; setDays(v => v.map((day, d) => d !== selected ? day : { ...day, items: (() => { const n = [...day.items]; const [item] = n.splice(dragged, 1); n.splice(to, 0, item); return n })() })); setDragged(null) }
  const remove = (id: string) => setDays(v => v.map((day, d) => d !== selected ? day : { ...day, items: day.items.filter(i => i.id !== id) }))
  const duplicate = (id: string) => setDays(v => v.map((day, d) => d !== selected ? day : { ...day, items: day.items.flatMap(item => item.id === id ? [item, { ...item, id: crypto.randomUUID(), title: `${item.title} (copy)` }] : [item]) }))
  const add = () => { if (!title.trim()) return; setDays(v => v.map((day, d) => d !== selected ? day : { ...day, items: [...day.items, { id: crypto.randomUUID(), time, title: title.trim(), category: 'custom' }].sort((a, b) => a.time.localeCompare(b.time)) })); setTitle(''); setAdding(false) }
  return <section id="itinerary" className="scroll-mt-24 rounded-2xl bg-[#173f30] p-5 text-white md:p-7">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-amber">Weather-aware itinerary</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Your day, optimized</h2><p className="mt-2 text-sm text-white/55">Drag activities to reorder. Weather follows each time slot.</p></div><Button variant="amber" onClick={() => optimize.mutate()} disabled={optimize.isPending}><Sparkles size={16} />{optimize.isPending ? 'Optimizing…' : 'Optimize my day'}</Button></div>
    <div className="no-scrollbar mt-7 flex gap-2 overflow-x-auto border-b border-white/10">{days.map((day, i) => <button key={day.date} onClick={() => setSelected(i)} className={`min-w-[94px] border-b-2 px-3 pb-3 text-left ${selected === i ? 'border-amber text-white' : 'border-transparent text-white/45'}`}><span className="block text-[10px] font-bold uppercase tracking-[.12em]">{day.label}</span><span className="mt-1 block text-sm font-semibold">{day.date}</span></button>)}</div>
    {days[selected]?.avoid && <div className="mt-5 flex flex-col gap-4 rounded-xl bg-amber p-4 text-ink sm:flex-row sm:items-center"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-ink text-amber"><CloudRain size={18} /></span><div className="flex-1"><p className="text-xs font-bold uppercase tracking-[.13em]">Weather change detected</p><p className="mt-1 text-sm">{days[selected].avoid} Consider moving outdoor plans indoors.</p></div><button onClick={() => optimize.mutate()} className="flex items-center gap-1 text-xs font-bold">Review & optimize <ArrowRight size={14} /></button></div>}
    <div className="mt-5 space-y-2">{items.map((item, i) => <div key={item.id} draggable onDragStart={() => setDragged(i)} onDragOver={e => e.preventDefault()} onDrop={() => move(i)} className="group flex items-center gap-3 rounded-xl border border-white/8 bg-white/[.06] p-3 transition hover:bg-white/[.1]"><GripVertical size={17} className="cursor-grab text-white/25" /><time className="w-12 shrink-0 text-sm font-semibold text-amber">{item.time}</time><span className="h-8 w-px bg-white/10" /><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{item.title}</h3><span className="text-[10px] uppercase tracking-[.1em] text-white/40">{item.category}</span></div>{item.weather_icon && <span className="rounded-lg bg-white/8 px-2.5 py-1.5 text-xs">{item.weather_icon} {item.temperature}°</span>}<button onClick={() => duplicate(item.id)} className="text-white/40 opacity-100 transition hover:text-white sm:opacity-0 sm:group-hover:opacity-100 focus:opacity-100" aria-label={`Duplicate ${item.title}`}><Copy size={14} /></button><button onClick={() => remove(item.id)} className="text-white/40 opacity-100 transition hover:text-red-300 sm:opacity-0 sm:group-hover:opacity-100 focus:opacity-100" aria-label="Delete"><Trash2 size={14} /></button></div>)}</div>
    {adding ? <div className="mt-3 grid gap-2 rounded-xl border border-white/15 bg-white/[.06] p-3 sm:grid-cols-[110px_1fr_auto]"><input type="time" value={time} onChange={event => setTime(event.target.value)} className="h-10 rounded-lg border border-white/15 bg-white/10 px-3 text-sm text-white outline-none focus:border-amber" /><input autoFocus value={title} onChange={event => setTitle(event.target.value)} onKeyDown={event => event.key === 'Enter' && add()} placeholder="Activity name" className="h-10 rounded-lg border border-white/15 bg-white/10 px-3 text-sm text-white outline-none placeholder:text-white/35 focus:border-amber" /><div className="flex gap-2"><Button variant="amber" size="sm" onClick={add}>Add</Button><Button variant="ghost" size="sm" className="text-white hover:bg-white/10" onClick={() => setAdding(false)}>Cancel</Button></div></div> : <button onClick={() => setAdding(true)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-white/20 py-3 text-xs font-semibold text-white/55 hover:border-white/40 hover:text-white"><Plus size={15} /> Add activity</button>}
  </section>
}
