import { ModernSelect } from '../../components/ui/ModernSelect'
import { useState } from 'react'
import { Check, Globe2, Languages, Save, Search } from 'lucide-react'
import { Button } from '../../components/ui/Button'
import { defaultLanguagePreferences, languages, regionalFormats, saveLanguagePreferences, useLanguagePreferences } from './preferences'

export function LanguageRegionSettings(){
  const saved=useLanguagePreferences()
  const [value,setValue]=useState(saved);const [message,setMessage]=useState('');const [error,setError]=useState('')
  const dirty=JSON.stringify(value)!==JSON.stringify(saved)
  const dateExample=new Intl.DateTimeFormat(value.formatLocale,{dateStyle:'long',timeZone:'UTC'}).format(new Date('2026-09-14T12:00:00Z'))
  const timeExample=new Intl.DateTimeFormat(value.formatLocale,{hour:'numeric',minute:'2-digit',hourCycle:value.hourCycle,timeZone:'UTC'}).format(new Date('2026-09-14T14:30:00Z'))
  function save(){try{saveLanguagePreferences(value);setMessage('Language and regional preferences saved on this device.');setError('')}catch{setError('Your browser could not save preferences. Allow browser storage and try again.')}}
  return <div><div className="flex items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-cream text-forest"><Globe2 size={22}/></span><div><h2 className="text-2xl font-semibold tracking-tight">Language &amp; region</h2><p className="mt-1 text-sm text-slate">Choose how AI plans and regional details appear.</p></div></div>
    <section className="mt-7 rounded-2xl border border-black/10 bg-cream p-4"><p className="text-sm font-semibold">Interface language: English</p><p className="mt-2 text-xs leading-5 text-slate">Menus, buttons, and system messages have not been translated yet. The choices below do not translate the interface or existing trips.</p></section>
    <div className="mt-7 space-y-6"><div><label htmlFor="ai-response-language" className="form-label">AI response language</label><ModernSelect id="ai-response-language" label="AI response language" value={value.aiLanguage} onValueChange={code=>{setValue({...value,aiLanguage:code});setMessage('')}} options={languages.map(item=>({value:item.code,label:item.label,description:item.native!==item.label?item.native:undefined,keywords:item.code,icon:<span className="text-[10px] font-bold">{item.code.toUpperCase()}</span>}))} searchable searchLabel="Find an AI response language" searchPlaceholder="Search language or native name…" footer={`${languages.length} language choices · Quality varies by language`} /><p className="mt-2 text-xs leading-5 text-slate">{languages.length} language choices. Gemini will be asked to write new activity titles and packing suggestions in your selected language. Quality varies by language; verify important information. Rule-based suggestions remain English.</p></div>
      <label className="block" htmlFor="regional-format"><span className="form-label">Regional format</span><ModernSelect id="regional-format" label="Regional format" value={value.formatLocale} onValueChange={locale=>{setValue({...value,formatLocale:locale});setMessage('')}} options={regionalFormats.map(([code,label])=>({value:code,label,description:code}))} searchable searchPlaceholder="Search regions or languages…" /><span className="mt-2 block text-xs leading-5 text-slate">Used for trip-list dates, share-link timestamps, and planner summary counts. This does not change the destination’s timezone or export formats.</span></label>
      <fieldset><legend className="form-label">Clock format</legend><div className="flex flex-wrap gap-3">{[['h23','24-hour'],['h12','12-hour']].map(([id,label])=><label key={id} className="flex items-center gap-2 rounded-xl border border-black/10 px-4 py-3 text-sm"><input type="radio" name="clock-format" checked={value.hourCycle===id} onChange={()=>{setValue({...value,hourCycle:id as 'h12'|'h23'});setMessage('')}} className="accent-emerald-800"/>{label}</label>)}</div></fieldset>
      <section className="rounded-2xl bg-cream p-5" aria-label="Regional format preview"><p className="eyebrow">Format preview</p><dl className="mt-4 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-slate">Date</dt><dd className="mt-1 text-sm font-semibold" data-testid="date-preview">{dateExample}</dd></div><div><dt className="text-xs text-slate">Time</dt><dd className="mt-1 text-sm font-semibold">{timeExample}</dd></div><div><dt className="text-xs text-slate">Number</dt><dd className="mt-1 text-sm font-semibold">{new Intl.NumberFormat(value.formatLocale).format(12345.67)}</dd></div></dl></section>
    </div>
    <div className="mt-7 flex flex-wrap items-center justify-between gap-3 border-t border-black/10 pt-5"><button type="button" className="min-h-11 text-sm font-semibold text-slate underline" onClick={()=>{setValue(defaultLanguagePreferences);setMessage('')}}>Reset to defaults</button><Button onClick={save} disabled={!dirty}><Save size={16}/>Save language preferences</Button></div>
    {message&&<p role="status" className="mt-4 flex items-center gap-2 text-sm text-forest"><Check size={16}/>{message}</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}<p className="mt-4 text-xs leading-5 text-slate">Preferences apply to this browser and device, not all devices on your account.</p>
  </div>
}
