import { draftDestinationForDate, type DraftStop } from '../journey/journey'
import { ModernSelect } from '../../components/ui/ModernSelect'
import { useState } from 'react'
import { ArrowDown, ArrowUp, CalendarDays, Plus, Trash2 } from 'lucide-react'
import type { InitialPlan } from '../../types'
import { Button } from '../../components/ui/Button'

export function DraftEditor({ draft, onChange, stops = [] }: { draft: InitialPlan; onChange: (value: InitialPlan) => void; stops?: DraftStop[] }) {
  const [selectedDay, setSelectedDay] = useState(0)
  const [tab, setTab] = useState<'itinerary' | 'packing'>('itinerary')
  const dayIndex = Math.min(selectedDay, Math.max(0, draft.itinerary.length - 1))
  const day = draft.itinerary[dayIndex]
  const changeItems = (items: InitialPlan['itinerary'][number]['items']) => onChange({ ...draft, itinerary: draft.itinerary.map((value,index) => index === dayIndex ? { ...value, items } : value) })
  const reorder = (index: number, delta: number) => { const items = [...day.items]; const to = index + delta; if (to < 0 || to >= items.length) return; [items[index], items[to]] = [items[to], items[index]]; changeItems(items) }
  return <div>
    <div className="flex flex-wrap gap-2 border-b border-black/10 pb-4" role="group" aria-label="Draft sections"><button type="button" aria-pressed={tab === 'itinerary'} className={`rounded-xl px-4 py-3 text-sm font-semibold ${tab === 'itinerary' ? 'bg-forest text-white' : 'bg-cream text-slate'}`} onClick={() => setTab('itinerary')}>Itinerary <span className="ml-1 opacity-70">{draft.itinerary.length} days</span></button><button type="button" aria-pressed={tab === 'packing'} className={`rounded-xl px-4 py-3 text-sm font-semibold ${tab === 'packing' ? 'bg-forest text-white' : 'bg-cream text-slate'}`} onClick={() => setTab('packing')}>Packing list <span className="ml-1 opacity-70">{draft.packing.length} items</span></button></div>
    {tab === 'itinerary' ? <div className="mt-5"><label htmlFor="draft-day" className="form-label">Choose a day</label><ModernSelect id="draft-day" label="Choose a day" value={String(dayIndex)} onValueChange={value=>setSelectedDay(Number(value))} options={draft.itinerary.map((day,index)=>({value:String(index),label:`Day ${index+1} · ${day.date}`,description:[draftDestinationForDate(stops,day.date)?.name,day.label].filter(Boolean).join(' · ')}))} searchable={draft.itinerary.length>6} searchPlaceholder="Search trip dates…" />
      {!day?.items.length && <div className="mt-5 rounded-2xl border border-dashed border-black/20 bg-cream px-5 py-9 text-center"><CalendarDays size={27} className="mx-auto text-forest" /><h3 className="mt-4 font-semibold">A little room for discovery.</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate">Add a walk, a meal, or something you’ve always wanted to do. You can also leave this day open.</p></div>}
      <div className="mt-5 space-y-3">{day?.items.map((item,index) => <div key={item.id} className="rounded-xl border border-black/10 bg-cream p-3"><div className="grid items-end gap-3 sm:grid-cols-[100px_minmax(0,1fr)]"><label><span className="form-label">Time</span><input dir="auto" aria-label={`Draft activity ${index+1} time`} type="time" className="form-input" value={item.time} onChange={e => changeItems(day.items.map(value => value.id === item.id ? { ...value, time:e.target.value } : value))} /></label><label><span className="form-label">Activity</span><input dir="auto" aria-label={`Draft activity ${index+1} title`} value={item.title} maxLength={180} className="form-input" placeholder="What would you like to do?" onChange={e => changeItems(day.items.map(value => value.id === item.id ? { ...value, title:e.target.value } : value))} /></label></div><div className="mt-2 flex items-center justify-between gap-2"><span className="text-xs text-slate">Activity {index+1}</span><div className="flex"><button type="button" className="grid h-10 w-10 place-items-center rounded-lg hover:bg-white disabled:opacity-30" aria-label={`Move draft activity ${index+1} up`} disabled={index === 0} onClick={() => reorder(index,-1)}><ArrowUp size={16}/></button><button type="button" className="grid h-10 w-10 place-items-center rounded-lg hover:bg-white disabled:opacity-30" aria-label={`Move draft activity ${index+1} down`} disabled={index === day.items.length-1} onClick={() => reorder(index,1)}><ArrowDown size={16}/></button><button type="button" className="grid h-10 w-10 place-items-center rounded-lg hover:bg-white" aria-label={`Remove draft activity ${index+1}`} onClick={() => changeItems(day.items.filter(value => value.id !== item.id))}><Trash2 size={16}/></button></div></div></div>)}</div>
      <Button type="button" className="mt-4" variant="secondary" disabled={!day || day.items.length>=50} onClick={() => changeItems([...day.items, {id:crypto.randomUUID(),title:'New activity',time:'09:00',category:'custom'}])}><Plus size={16}/>Add activity</Button><p className="mt-3 text-xs leading-5 text-slate">Times are local to {draftDestinationForDate(stops,day?.date||'')?.name||'this stop'} ({draftDestinationForDate(stops,day?.date||'')?.timezone||'destination timezone'}). Verify opening times, travel time, and accessibility yourself.</p>
    </div> : <div className="mt-5"><p className="mb-4 text-sm text-slate">Make this list your own. Nothing is marked as packed automatically.</p><div className="space-y-3">{draft.packing.map((item,index) => <div key={item.id} className="grid items-end gap-2 rounded-xl border border-black/10 bg-cream p-3 sm:grid-cols-[minmax(0,1fr)_80px_40px]"><label><span className="form-label">Item</span><input className="form-input" dir="auto" aria-label={`Draft packing item ${index+1}`} value={item.name} maxLength={180} onChange={e => onChange({...draft,packing:draft.packing.map(value => value.id===item.id ? {...value,name:e.target.value}:value)})}/></label><label><span className="form-label">Qty</span><input className="form-input" aria-label={`Draft packing quantity ${index+1}`} type="number" min={1} max={99} value={item.quantity} onChange={e => onChange({...draft,packing:draft.packing.map(value => value.id===item.id ? {...value,quantity:Number(e.target.value)}:value)})}/></label><button type="button" aria-label={`Remove draft packing item ${index+1}`} className="grid h-12 w-10 place-items-center rounded-lg" onClick={() => onChange({...draft,packing:draft.packing.filter(value=>value.id!==item.id)})}><Trash2 size={16}/></button></div>)}</div><Button type="button" variant="secondary" className="mt-4" disabled={draft.packing.length>=300} onClick={() => onChange({...draft,packing:[...draft.packing,{id:crypto.randomUUID(),name:'New item',quantity:1,packed:false,category:'My essentials'}]})}><Plus size={16}/>Add packing item</Button></div>}
  </div>
}
