import { orderDestinations, destinationDescription } from '../features/destinations/orderDestinations'
import { ModernSelect } from '../components/ui/ModernSelect'
import { useEffect, useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, CloudRain, GitCompareArrows, Sparkles, Sun, ThermometerSun, Wind } from 'lucide-react'
import { Link } from 'react-router-dom'
import { AppShell } from '../layouts/AppShell'
import { Skeleton } from '../components/ui/Skeleton'
import { WeatherIcon } from '../components/ui/WeatherIcon'
import { api } from '../services/api'

export function ComparisonPage() {
  const destinations = useQuery({ queryKey: ['destinations', ''], queryFn: () => api.searchDestinations(''), staleTime: 600_000 })
  const ordered = useMemo(() => orderDestinations(destinations.data || []), [destinations.data])
  const [selected, setSelected] = useState<string[]>([])
  useEffect(() => { if (!selected.length && destinations.data?.length) setSelected(ordered.slice(0, 3).map(item => item.id)) }, [destinations.data, ordered, selected.length])
  const chosen = selected.map(id => destinations.data?.find(item => item.id === id)).filter(Boolean)
  const weather = useQuery({ queryKey: ['comparison-weather', ...selected], queryFn: () => Promise.all(chosen.map(destination => api.getCurrentWeather(destination!.latitude, destination!.longitude))), enabled: chosen.length === 3, staleTime: 600_000 })
  const update = (index: number, id: string) => setSelected(current => current.map((value, i) => i === index ? id : value))
  return <AppShell><main className="mx-auto max-w-6xl px-5 pb-28 pt-8 md:px-8 lg:px-10 lg:pb-16 lg:pt-10"><Link to="/app/explore" className="inline-flex items-center gap-2 text-xs font-bold text-forest"><ArrowLeft size={14} />Back to explore</Link><div className="mt-6"><p className="eyebrow">Side by side</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Compare destinations</h1><p className="mt-3 text-sm text-slate">A practical snapshot of current conditions and travel comfort.</p></div>
    <div className="mt-8 grid gap-3 md:grid-cols-3">{[0,1,2].map(index => <label key={index} className="rounded-xl border border-black/8 bg-white p-3"><span className="form-label">Destination {index + 1}</span><ModernSelect label={`Destination ${index+1}`} value={selected[index]||''} onValueChange={id=>update(index,id)} options={ordered.map(destination=>({value:destination.id,label:destination.name,description:destinationDescription(destination,ordered),icon:destination.flag}))} placeholder="Choose a destination" footer="Destinations A–Z" searchable searchPlaceholder="Search destinations…" disabled={destinations.isLoading} /></label>)}</div>
    {weather.isError ? <div role="alert" className="mt-6 rounded-2xl border border-black/10 bg-white p-6 text-sm text-slate">Weather could not be loaded. <button className="font-semibold underline" onClick={()=>weather.refetch()}>Retry</button></div> : weather.isLoading || !weather.data || chosen.length < 3 ? <Skeleton className="mt-6 h-[520px] rounded-2xl" /> : <section className="mt-6 overflow-x-auto rounded-2xl border border-black/8 bg-white"><div className="grid grid-cols-[120px_repeat(3,minmax(160px,1fr))] border-b border-black/8 bg-[#173f30] text-white"><div className="p-4" />{chosen.map((destination, index) => <div key={`${destination!.id}-${index}`} className="border-l border-white/10 p-5 text-center"><span className="text-3xl">{destination!.flag}</span><h2 className="mt-2 text-xl font-semibold">{destination!.name}</h2><p className="mt-1 text-[10px] text-white/50">{destination!.country}</p></div>)}</div><ComparisonRow label="Conditions" icon={Sun} values={weather.data!.map((item, index) => <span className="flex flex-col items-center gap-2"><WeatherIcon name={item.icon} className="h-7 w-7" /><strong>{item.condition}</strong><small className="text-slate">Feels like {item.feels_like}°</small></span>)} /><ComparisonRow label="Temperature" icon={ThermometerSun} values={weather.data!.map(item => <strong className="text-2xl">{item.temperature}°</strong>)} /><ComparisonRow label="Rain risk" icon={CloudRain} values={weather.data!.map(item => <span><strong className="text-lg">{item.precipitation}%</strong><small className="mt-1 block text-slate">{item.precipitation < 25 ? 'Low' : item.precipitation < 55 ? 'Moderate' : 'High'}</small></span>)} /><ComparisonRow label="Wind" icon={Wind} values={weather.data!.map(item => <span><strong>{item.wind} km/h</strong><small className="mt-1 block text-slate">{item.wind < 20 ? 'Comfortable' : 'Breezy'}</small></span>)} /><ComparisonRow label="Travel score" icon={Sparkles} emphasized values={weather.data!.map(item => { const score = Math.max(45, Math.round(100 - item.precipitation * .3 - Math.abs(item.temperature - 24) * 2 - Math.max(0, item.wind - 12))); return <span><strong className="text-3xl text-forest">{score}</strong><small className="mt-1 block font-semibold text-slate">{score >= 85 ? 'Excellent' : score >= 70 ? 'Good' : 'Mixed'}</small></span> })} /></section>}
    <p className="mt-4 text-center text-[10px] leading-5 text-slate">Comparison uses current normalized provider data. The Travel Weather Score is a planning heuristic, not a scientific safety rating.</p>
  </main></AppShell>
}
function ComparisonRow({ label, icon: Icon, values, emphasized = false }: { label: string; icon: typeof Sun; values: React.ReactNode[]; emphasized?: boolean }) { return <div className={`grid grid-cols-[120px_repeat(3,minmax(160px,1fr))] border-b border-black/7 last:border-0 ${emphasized ? 'bg-[#f5f2e9]' : ''}`}><div className="flex flex-col justify-center gap-2 p-4 text-xs font-semibold text-slate"><Icon size={16} />{label}</div>{values.map((value, index) => <div key={index} className="flex min-h-24 items-center justify-center border-l border-black/7 p-4 text-center text-sm">{value}</div>)}</div> }
