import { formatTripDate } from '../features/locale/preferences'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { CalendarDays, Plus, LockKeyhole } from 'lucide-react'
import { AppShell } from '../layouts/AppShell'
import { Skeleton } from '../components/ui/Skeleton'
import { api } from '../services/api'
import { getSession } from '../features/auth/session'
export function DashboardPage() {
  const trips = useQuery({ queryKey: ['trips'], queryFn: api.listTrips, retry: false })
  const user = getSession()?.user
  return <AppShell><main className="mx-auto max-w-6xl px-5 py-10 pb-28 md:px-8"><p className="eyebrow">Your private travel desk</p><div className="mt-3 flex flex-wrap items-center justify-between gap-5"><div><h1 className="text-4xl font-semibold tracking-tight">Welcome, {user?.display_name || user?.email.split('@')[0]}</h1><p className="mt-3 text-slate">Plan your journey with live destination weather and saved travel details.</p></div><Link to="/planner" className="flex items-center gap-2 rounded-xl bg-forest px-5 py-3 font-semibold text-white"><Plus size={18} />Plan a trip</Link></div><div className="mt-8 flex items-center gap-2 text-sm text-slate"><LockKeyhole size={16} />Trips are private unless you create a sharing link. You can revoke access at any time.</div><h2 className="mt-9 text-2xl font-semibold">Your trips</h2>{trips.isLoading ? <Skeleton className="mt-5 h-64 w-full" /> : trips.isError ? <p role="alert" className="mt-5">{trips.error.message} <button onClick={() => trips.refetch()} className="underline">Retry</button></p> : trips.data?.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{trips.data.map(trip => <Link to={`/trip/${trip.id}`} key={trip.id} className="rounded-2xl border border-black/10 bg-white p-6 hover:border-forest"><span className="text-3xl">{trip.destination.flag}</span><h3 className="mt-4 text-2xl font-semibold">{trip.title}</h3><p className="mt-2 text-sm text-slate">{trip.stops?.length&&trip.stops.length>1?`${trip.stops.length} stops · ${trip.stops.map(stop=>stop.destination.name).join(' → ')}`:trip.destination.country}</p><p className="mt-5 flex items-center gap-2 text-xs text-slate"><CalendarDays size={14} />{formatTripDate(trip.departure_date)} – {formatTripDate(trip.return_date)}</p><p className="mt-5 text-sm font-semibold text-forest">Open itinerary & packing →</p></Link>)}</div> : <section className="mt-5 rounded-2xl border border-dashed border-black/20 bg-white p-10 text-center"><h3 className="text-xl font-semibold">No trips yet</h3><p className="mt-3 text-slate">Your new account starts with an empty, private workspace.</p><Link to="/planner" className="mt-5 inline-block font-semibold text-forest underline">Create your first trip</Link></section>}</main></AppShell>
}
