import { defaultDeparture, defaultReturn } from '../lib/tripDates'
import { useQuery } from '@tanstack/react-query'
import { ArrowRight, GitCompareArrows, Heart, Map, MapPin, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AppShell } from '../layouts/AppShell'
import { Button } from '../components/ui/Button'
import { Skeleton } from '../components/ui/Skeleton'
import { DestinationSearch } from '../features/destinations/DestinationSearch'
import { useSavedDestinations } from '../hooks/useSavedDestinations'
import { api } from '../services/api'
import type { Destination } from '../types'

export function ExplorePage() {
  const navigate = useNavigate(); const [selected, setSelected] = useState<Destination | null>(null); const { isSaved, toggle } = useSavedDestinations()
  const destinations = useQuery({ queryKey: ['destinations', ''], queryFn: () => api.searchDestinations(''), staleTime: 600_000 })
  const plan = (destination: Destination) => navigate('/planner', { state: { destination, departure: defaultDeparture, returnDate: defaultReturn } })
  return <AppShell><main className="mx-auto max-w-6xl px-5 pb-28 pt-8 md:px-8 lg:px-10 lg:pb-16 lg:pt-10"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="eyebrow">Destination discovery</p><h1 className="mt-3 text-[clamp(1.9rem,8vw,2.25rem)] font-semibold tracking-[-.04em] md:text-6xl">Find your next<br />good-weather escape.</h1><p className="mt-5 max-w-xl text-base leading-7 text-slate">Search cities and compare the conditions that matter to how you travel.</p></div><div className="rounded-2xl border border-black/8 bg-white p-4 shadow-card"><DestinationSearch value={selected} onSelect={setSelected} variant="plain" />{selected && <div className="mt-3 flex items-center gap-3 rounded-xl bg-[#eef1e9] p-3"><span className="text-3xl">{selected.flag}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Ready to explore {selected.name}?</p><p className="text-[11px] text-slate">We’ll personalize dates and activities next.</p></div><Button size="sm" onClick={() => plan(selected)}>Plan <ArrowRight size={14} /></Button></div>}</div></div>
    <section className="mt-12"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Popular right now</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.03em]">Weather-worthy destinations</h2></div><div className="flex gap-2"><Link to="/app/saved"><Button variant="secondary" size="sm"><Heart size={15} />Saved</Button></Link><Link to="/app/compare"><Button variant="secondary" size="sm"><GitCompareArrows size={15} />Compare</Button></Link></div></div>
      {destinations.isLoading ? <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(i => <Skeleton key={i} className="h-60 rounded-2xl" />)}</div> : <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{destinations.data?.slice(0, 6).map((destination, index) => <article key={destination.id} className={`relative overflow-hidden rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:shadow-soft ${index === 0 ? 'border-transparent bg-[#173f30] text-white' : 'border-black/8 bg-white'}`}><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-full bg-white/90 text-2xl shadow-sm">{destination.flag}</span><button onClick={() => toggle(destination)} aria-label={`${isSaved(destination.id) ? 'Remove' : 'Save'} ${destination.name}`} className={`grid h-9 w-9 place-items-center rounded-full border ${index === 0 ? 'border-white/20 text-white' : 'border-black/10 text-slate'} ${isSaved(destination.id) ? 'bg-amber text-ink' : ''}`}><Heart size={16} fill={isSaved(destination.id) ? 'currentColor' : 'none'} /></button></div><p className={`mt-8 flex items-center gap-1 text-[10px] font-bold uppercase tracking-[.15em] ${index === 0 ? 'text-amber' : 'text-forest'}`}><MapPin size={12} />{destination.country}</p><h3 className="mt-2 text-2xl font-semibold">{destination.name}</h3><p className={`mt-2 text-xs ${index === 0 ? 'text-white/50' : 'text-slate'}`}>{destination.timezone}</p><div className="mt-6 flex items-center justify-between"><button onClick={() => plan(destination)} className={`flex items-center gap-2 text-xs font-bold ${index === 0 ? 'text-white' : 'text-forest'}`}>Plan this trip <ArrowRight size={14} /></button><span className={`text-[10px] ${index === 0 ? 'text-white/40' : 'text-slate'}`}>{destination.latitude.toFixed(1)}°, {destination.longitude.toFixed(1)}°</span></div></article>)}</div>}
    </section>
    <section className="mt-10 grid gap-4 md:grid-cols-2"><Link to="/app/compare" className="group rounded-2xl bg-[#e8dfc9] p-6"><GitCompareArrows className="text-forest" /><h3 className="mt-8 text-xl font-semibold">Compare destination conditions</h3><p className="mt-2 text-sm text-slate">See temperature, rain risk, and travel suitability side by side.</p><span className="mt-5 flex items-center gap-2 text-xs font-bold text-forest">Start comparing <ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></Link><Link to="/app/weather-map" className="group rounded-2xl bg-[#dfe8e0] p-6"><Map className="text-forest" /><h3 className="mt-8 text-xl font-semibold">Explore the weather map</h3><p className="mt-2 text-sm text-slate">Inspect destination conditions with temperature, rain, and wind layers.</p><span className="mt-5 flex items-center gap-2 text-xs font-bold text-forest">Open map <ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></Link></section>
  </main></AppShell>
}
