import { StopEditor } from '../features/journey/StopEditor'
import { stopPayload, validateJourney, type DraftStop } from '../features/journey/journey'
import { ModernSelect } from '../components/ui/ModernSelect'
import { formatTripDate, languageName, useLanguagePreferences } from '../features/locale/preferences'
import { Link } from 'react-router-dom'
import { useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, ArrowRight, CalendarDays, Check, Compass, LockKeyhole, MapPin, NotebookPen, ShieldCheck, Sparkles, WandSparkles } from 'lucide-react'
import { Logo } from '../components/brand/Logo'
import { Button } from '../components/ui/Button'
import { Skeleton } from '../components/ui/Skeleton'
import { ThemeToggle } from '../features/theme/ThemeToggle'
import { DestinationSearch } from '../features/destinations/DestinationSearch'
import { DraftEditor } from '../features/planning/DraftEditor'
import { defaultDeparture, defaultReturn, todayDate } from '../lib/tripDates'
import { api } from '../services/api'
import type { Destination, DraftResult, InitialPlan } from '../types'

const steps = ['Your approach', 'Trip details', 'Make it yours', 'Review & create']
const interests = [['sightseeing','Culture & sightseeing'],['walking','Walking'],['nature','Nature'],['food','Food & cafés'],['hiking','Hiking'],['shopping','Markets & shopping']]
const styles = [['relaxed','Relaxed'],['adventure','Adventure'],['business','Business'],['family','Family'],['romantic','Romantic'],['backpacking','Backpacking']]
const daysBetween = (start: string,end: string) => Math.round((Date.parse(`${end}T12:00:00Z`)-Date.parse(`${start}T12:00:00Z`))/86400000)+1
function blankPlan(start:string,end:string): InitialPlan {
  return { itinerary:Array.from({length:daysBetween(start,end)},(_,index)=>{const date=new Date(`${start}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+index);return {date:date.toISOString().slice(0,10),label:date.toLocaleDateString('en',{weekday:'long',timeZone:'UTC'}),headline:'Your itinerary',items:[]}}), packing:['Travel documents','Phone charger','Personal essentials'].map(name=>({id:crypto.randomUUID(),name,quantity:1,packed:false,category:'Travel essentials'})) }
}

export function PlannerPage() {
  const languagePreferences = useLanguagePreferences()
  const location = useLocation(); const navigate = useNavigate(); const client = useQueryClient()
  const initial = location.state as {destination?:Destination;departure?:string;returnDate?:string}|null
  const [step,setStep]=useState(0); const [mode,setMode]=useState<'manual'|'ai'>('manual')
  const [stopDrafts,setStopDrafts]=useState<DraftStop[]>([{key:crypto.randomUUID(),destination:initial?.destination||null,arrival_date:initial?.departure||defaultDeparture,departure_date:initial?.returnDate||defaultReturn}])
  const destination=stopDrafts[0]?.destination||null
  const departure=stopDrafts[0]?.arrival_date||''; const returnDate=stopDrafts.at(-1)?.departure_date||''
  const journeyErrors=validateJourney(stopDrafts,todayDate)
  const [title,setTitle]=useState(''); const [style,setStyle]=useState('relaxed'); const [pace,setPace]=useState<'easy'|'balanced'|'active'>('balanced')
  const [activities,setActivities]=useState(['sightseeing','walking','food']); const [notes,setNotes]=useState(''); const [consent,setConsent]=useState(false)
  const [draft,setDraft]=useState<InitialPlan|null>(null); const [result,setResult]=useState<DraftResult|null>(null)
  const [pending,setPending]=useState<'ai'|'guided'|'save'|null>(null); const [error,setError]=useState(''); const [edited,setEdited]=useState(false)
  const requestId=useRef(crypto.randomUUID()); const heading=useRef<HTMLHeadingElement>(null); const completed=useRef(false)
  const options=useQuery({queryKey:['planning-options'],queryFn:api.planningOptions,retry:false,staleTime:60000})
  const dayCount=daysBetween(departure,returnDate)
  const validDates=!!departure&&!!returnDate&&Number.isFinite(dayCount)&&dayCount>=1&&dayCount<=61&&departure>=todayDate&&journeyErrors.length===0
  const assistantAllowed=validDates&&dayCount<=14
  useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})},[step])
  useEffect(()=>{requestId.current=crypto.randomUUID()},[draft,title,destination,departure,returnDate,style,activities,stopDrafts])
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(edited&&!completed.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[edited])
  const go=(next:number)=>{setError('');setStep(next)}
  function changeDraft(value:InitialPlan){setDraft(value);setEdited(true);setError('')}
  function invalidate(){setDraft(null);setResult(null);setEdited(true);setError('')}
  function detailsNext(){
    if(journeyErrors.length){setError(journeyErrors[0]);return}
    if(!destination)return
    if(!validDates){setError('Choose valid dates from today onward. Trips can last up to 61 days.');return}
    if(!draft)setDraft(blankPlan(departure,returnDate));setEdited(true);go(2)
  }
  async function generate(source:'ai'|'guided'){
    if(!destination||!assistantAllowed)return
    if(draft?.itinerary.some(day=>day.items.length)&&!window.confirm('Replace your current draft with new suggestions? Your trip has not been saved yet.'))return
    setPending(source);setError('')
    try{const value=await api.generatePlanDraft({destination_id:destination.id,stops:stopPayload(stopDrafts),departure_date:departure,return_date:returnDate,travel_style:style,activities,mode:source,pace,notes,output_language:languagePreferences.aiLanguage,ai_consent:source==='ai'&&consent});setDraft(value.draft);setResult(value);setEdited(true);go(3)}
    catch(e){setError(e instanceof Error?e.message:'Could not prepare a draft. Your details are still here.')}
    finally{setPending(null)}
  }
  const draftValid=!!draft&&draft.itinerary.every(day=>day.items.every(item=>item.title.trim()&&/^([01]\d|2[0-3]):[0-5]\d$/.test(item.time)))&&draft.packing.every(item=>item.name.trim()&&Number.isInteger(item.quantity)&&item.quantity>=1&&item.quantity<=99)
  async function create(){
    if(!destination||!draft||!draftValid||!validDates)return
    setPending('save');setError('')
    try{const value=await api.createTrip({title:title.trim()||(stopDrafts.length>1?stopDrafts.map(stop=>stop.destination!.name).join(' → ').slice(0,180):`${destination.name} trip`),destination_id:destination.id,stops:stopPayload(stopDrafts),departure_date:departure,return_date:returnDate,travel_style:style,activities,initial_plan:draft,request_id:requestId.current});completed.current=true;await client.invalidateQueries({queryKey:['trips']});navigate(`/trip/${value.id}`,{replace:true})}
    catch(e){setError(e instanceof Error?e.message:'Could not save your trip. Your draft is still here.')}
    finally{setPending(null)}
  }
  const leave=()=>{if(!edited||window.confirm('Leave the planner? This draft has not been saved yet.'))navigate('/app')}
  const totalActivities=draft?.itinerary.reduce((sum,day)=>sum+day.items.length,0)||0
  return <div className="professional-planner min-h-screen bg-cream text-ink">
    <header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-5 py-5 md:px-8"><Logo/><div className="flex items-center gap-3"><ThemeToggle/><button type="button" className="flex min-h-11 items-center gap-2 text-sm font-semibold text-slate" disabled={!!pending} onClick={leave}><ArrowLeft size={16}/>Back to workspace</button></div></div></header>
    <main className="mx-auto max-w-7xl px-5 py-7 md:px-8 md:py-10">
      <nav aria-label="Trip planning progress" className="mb-9"><ol className="grid grid-cols-4 gap-2 sm:gap-4">{steps.map((label,index)=><li key={label} aria-current={step===index?'step':undefined} className={`border-t-2 pt-3 ${step>=index?'border-forest':'border-black/10'}`}><span className={`mb-2 grid h-7 w-7 place-items-center rounded-full text-xs font-semibold ${step>=index?'bg-forest text-white':'bg-white text-slate'}`}>{step>index?<Check size={14}/>:index+1}</span><span className={`block text-[11px] font-semibold sm:text-sm ${step===index?'text-ink':'text-slate'}`}>{label}</span></li>)}</ol></nav>
      <div className="grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_290px]">
        <div className="min-w-0">
          <section className="rounded-3xl border border-black/10 bg-white p-5 shadow-card sm:p-8 lg:p-9" aria-busy={!!pending}>
            <p className="eyebrow">{step===0?'A trip that feels like you':step===1?'Start with the essentials':step===2?'You set the direction':'One last look'}</p>
            <h1 ref={heading} tabIndex={-1} className="mt-4 text-[clamp(1.8rem,4vw,2.7rem)] font-semibold leading-tight tracking-[-.045em] outline-none">{step===0?'How would you like to plan?':step===1?'Where are we heading?':step===2?(mode==='manual'?'Build it your way.':'Tell us what a great trip looks like.'):'Your trip, ready when you are.'}</h1>
            <p className="mt-3 text-sm leading-6 text-slate">{step===0?'Start with a blank canvas or get help with a first draft. Either way, every detail stays in your hands.':step===1?'One journey, as many as 12 stops. Choose where each day belongs.':step===2?(mode==='manual'?'Add your own activities and packing items. Open days are welcome, too.':'Choose your pace and interests. You’ll review every suggestion before anything is saved.'):'Review and edit the details below. Creating your trip saves the itinerary and packing list together. Afterwards, link real places and add durations to calculate directions.'}</p>
            <fieldset disabled={!!pending} className="mt-7 min-w-0">
              {step===0&&<><fieldset><legend className="sr-only">Planning approach</legend><div className="grid gap-4 sm:grid-cols-2">{[{id:'manual' as const,icon:NotebookPen,title:'Plan manually',copy:'You know what you want. Build an itinerary from scratch, at your own pace.',points:['Choose every activity','Create your own packing list','No AI or external AI sharing']},{id:'ai' as const,icon:Sparkles,title:'Use AI assistance',copy:'Bring your ideas. Get an editable first draft shaped by your preferences.',points:['Describe the trip you want','Review suggestions before saving','Keep, change, or remove anything']}].map(({id,icon:Icon,title:label,copy,points})=><label key={id} className={`planner-choice cursor-pointer rounded-2xl border-2 p-5 ${mode===id?'border-forest bg-cream':'border-black/10 bg-white'}`}><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-forest text-white"><Icon size={22}/></span><input type="radio" aria-label={label} name="planning-mode" value={id} checked={mode===id} onChange={()=>{setMode(id);setError('')}} className="h-5 w-5 accent-emerald-800"/><span className="sr-only">{label}</span></div><h2 className="mt-6 text-xl font-semibold">{label}</h2><p className="mt-3 text-sm leading-6 text-slate">{copy}</p><ul className="mt-5 space-y-3 text-xs text-slate">{points.map(point=><li key={point} className="flex items-start gap-2"><Check size={14} className="mt-px shrink-0 text-forest"/>{point}</li>)}</ul>{id==='ai'&&<p className="mt-5 text-xs font-semibold text-forest">{options.isLoading?'Checking AI availability…':options.data?.ai_available?`${options.data.provider || 'AI provider'} configured`:options.isError?'AI availability could not be checked':'AI connection required · rule-based alternative available'}</p>}</label>)}</div></fieldset><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-slate"><LockKeyhole size={15} className="mt-0.5 shrink-0"/>Your trip is private. Nothing is booked or shared automatically.</p></>}
              {step===1&&<div className="space-y-6">{draft&&<p className="rounded-xl bg-cream p-3 text-xs text-slate">Changing stops resets the current unsaved draft. Review the schedule before continuing.</p>}<StopEditor stops={stopDrafts} minDate={todayDate} onChange={next=>{setStopDrafts(next);invalidate()}}/><label className="block" htmlFor="planner-title"><span className="form-label">Trip name <span className="font-normal normal-case tracking-normal">(optional)</span></span><input id="planner-title" className="form-input" maxLength={180} value={title} placeholder={destination?`${destination.name} trip`:'Give your journey a name'} onChange={e=>{setTitle(e.target.value);setEdited(true)}}/></label><label className="block" htmlFor="planner-style"><span className="form-label">Travel style</span><ModernSelect id="planner-style" label="Travel style" value={style} onValueChange={setStyle} options={styles.map(([value,label])=>({value,label}))} searchable={false} /></label><div className="rounded-xl bg-cream p-4 text-xs leading-5 text-slate">Dates beyond the forecast window are welcome. The app will tell you when weather data is not yet available, rather than predict conditions months ahead.</div></div>}
              {step===2&&mode==='manual'&&draft&&<DraftEditor draft={draft} onChange={changeDraft} stops={stopDrafts}/>}
              {step===2&&mode==='ai'&&<div className="space-y-6"><fieldset><legend className="form-label">Your preferred pace</legend><div className="grid grid-cols-3 gap-2">{[['easy','Easy','2 activities/day'],['balanced','Balanced','3 activities/day'],['active','Active','4 activities/day']].map(([id,label,description])=><button type="button" key={id} aria-pressed={pace===id} onClick={()=>setPace(id as typeof pace)} className={`rounded-xl border px-2 py-4 text-center ${pace===id?'border-forest bg-forest text-white':'border-black/10 bg-cream text-ink'}`}><span className="block text-sm font-semibold">{label}</span><span className="mt-1 block text-[10px] opacity-75">{description}</span></button>)}</div></fieldset><fieldset><legend className="form-label">What would you love to do?</legend><div className="flex flex-wrap gap-2">{interests.map(([id,label])=><button type="button" key={id} aria-pressed={activities.includes(id)} onClick={()=>setActivities(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id])} className={`min-h-11 rounded-full border px-4 py-2 text-xs font-semibold ${activities.includes(id)?'border-forest bg-forest text-white':'border-black/10 text-slate'}`}>{label}</button>)}</div></fieldset><label className="block" htmlFor="planner-notes"><span className="form-label">Anything else we should know?</span><textarea id="planner-notes" rows={4} maxLength={1500} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="For example: a relaxed trip with local food, art, and time to rest. Avoid long walks." className="w-full resize-y rounded-xl border border-black/10 bg-cream p-4 text-sm outline-none focus:border-forest"/><span className="mt-2 block text-xs text-slate">Optional · {notes.length}/1500 characters. Don’t include sensitive personal information.</span></label>{!assistantAllowed&&<div role="alert" className="rounded-xl border border-amber/50 bg-cream p-4 text-sm">Assisted drafts cover up to 14 days. You can plan this longer trip manually.</div>}
                <div className="rounded-xl border border-black/10 bg-cream p-4 text-sm"><p>AI response language: <strong>{languageName(languagePreferences.aiLanguage)}</strong></p><Link to="/app/settings/language" target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs font-semibold text-forest underline">Change language in Settings (new tab)</Link></div>{options.data?.ai_available?<label className="flex items-start gap-3 rounded-xl bg-cream p-4 text-xs leading-5 text-slate"><input type="checkbox" className="mt-1 h-4 w-4 shrink-0 accent-emerald-800" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to send my destinations, stop dates, interests, pace, notes, and available forecast to {options.data?.provider || 'the configured AI provider'} to generate this draft. My account details are not sent.</label>:<div className="rounded-xl border border-black/10 bg-cream p-4"><p className="text-sm font-semibold">AI assistance isn’t connected yet</p><p className="mt-2 text-xs leading-5 text-slate">An administrator needs to configure the AI provider key. You can still plan manually or use rule-based suggestions. Rule-based suggestions are not AI and do not interpret your notes.</p>{options.isError&&<button type="button" className="mt-3 text-xs font-semibold underline" onClick={()=>options.refetch()}>Check connection again</button>}</div>}
                <div className="flex flex-wrap gap-3"><Button type="button" size="lg" onClick={()=>generate('ai')} disabled={!options.data?.ai_available||!consent||!assistantAllowed}><Sparkles size={17}/>Generate AI draft</Button><Button type="button" variant="secondary" disabled={!assistantAllowed} onClick={()=>generate('guided')}><WandSparkles size={16}/>Use rule-based suggestions</Button></div><button type="button" className="text-sm font-semibold text-forest underline underline-offset-4" onClick={()=>{setMode('manual');setError('')}}>Switch to manual planning</button></div>}
              {step===3&&draft&&<><div className="mb-6 rounded-xl border border-black/10 bg-cream p-4"><p className="text-sm font-semibold">{result?.source||'Your manually created draft'}</p>{result?.output_language&&<p className="mt-2 text-xs text-slate">Requested draft language: {languageName(result.output_language)}</p>}<p className="mt-2 text-xs leading-5 text-slate">{result?`Weather source: ${result.weather_source.replaceAll('_',' ')} · ${result.forecast_days} days with forecast data.`:'No AI was used to generate this plan. Live weather will be shown in your saved trip.'}</p>{result?.warnings.map(warning=><p key={warning} className="mt-2 text-xs leading-5 text-slate">{warning}</p>)}</div><DraftEditor draft={draft} onChange={changeDraft} stops={stopDrafts}/></>}
            </fieldset>
            {pending&&<div role="status" className="mt-6 rounded-2xl bg-cream p-5"><p className="mb-4 text-sm font-semibold">{pending==='save'?'Saving your private trip…':pending==='ai'?'Preparing your AI draft…':'Preparing rule-based suggestions…'}</p><div className="space-y-3"><Skeleton className="h-3 w-3/4"/><Skeleton className="h-3 w-full"/><Skeleton className="h-3 w-1/2"/></div><p className="mt-4 text-xs text-slate">{pending==='save'?'Your itinerary and packing list are saved together.':'This may take a moment. Nothing will be saved until you review and create the trip.'}</p></div>}
            {error&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
            {(step===2||step===3)&&draft&&!draftValid&&<p role="status" className="mt-4 text-sm text-red-700">Give every activity and packing item a name, use valid times, and choose quantities from 1 to 99.</p>}
            <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-black/10 pt-6"><Button type="button" variant="ghost" disabled={!!pending} onClick={()=>step===0?leave():go(step-1)}><ArrowLeft size={16}/>{step===0?'Cancel':'Back'}</Button>{step===0&&<Button type="button" size="lg" onClick={()=>go(1)}>Continue <ArrowRight size={17}/></Button>}{step===1&&<Button type="button" size="lg" onClick={detailsNext}>Continue <ArrowRight size={17}/></Button>}{step===2&&mode==='manual'&&<Button type="button" size="lg" disabled={!draftValid||!!pending} onClick={()=>go(3)}>Review my trip <ArrowRight size={17}/></Button>}{step===3&&<Button type="button" size="lg" disabled={!draftValid||!!pending} onClick={create}><Check size={17}/>{pending==='save'?'Creating…':'Create my trip'}</Button>}</div>
          </section>
          <p className="mt-5 flex items-start gap-2 px-1 text-xs leading-5 text-slate"><ShieldCheck size={15} className="mt-0.5 shrink-0"/>Weather guidance is not a guarantee. Suggestions do not confirm bookings, safety, or venue availability.</p>
        </div>
        <aside className="planner-summary rounded-3xl bg-[#173f30] p-6 text-white lg:sticky lg:top-6"><span className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-white/70"><Compass size={15}/>Your journey at a glance</span><h2 className="mt-7 text-2xl font-semibold tracking-tight">{title.trim()||destination?.name||'Somewhere worth going.'}</h2><p className="mt-2 text-sm text-white/70">{destination?.country||'Start with a destination. Make it your own.'}</p><div className="mt-7 space-y-5 border-t border-white/20 pt-5"><div className="flex gap-3"><MapPin size={17} className="mt-1 shrink-0 text-amber"/><div><p className="text-[10px] uppercase tracking-widest text-white/55">Destination</p><p className="mt-1 text-sm">{stopDrafts.map((stop,index)=><span className="block" key={stop.key}>{index+1}. {stop.destination?.name||'Not selected yet'}</span>)}</p><p className="mt-1 text-xs text-white/60">{stopDrafts.length>1?'Each stop uses its own local timezone':destination?.timezone||'Search cities, countries, and landmarks'}</p></div></div><div className="flex gap-3"><CalendarDays size={17} className="mt-1 shrink-0 text-amber"/><div><p className="text-[10px] uppercase tracking-widest text-white/55">Travel dates</p><p className="mt-1 text-sm">{departure?formatTripDate(departure,languagePreferences.formatLocale):'Choose departure'}<br/>{returnDate?formatTripDate(returnDate,languagePreferences.formatLocale):'Choose return'}</p>{validDates&&<p className="mt-1 text-xs text-white/60">{dayCount} {dayCount===1?'day':'days'} · {Math.max(0,dayCount-1)} nights</p>}</div></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-3"><strong className="block text-xl">{new Intl.NumberFormat(languagePreferences.formatLocale).format(totalActivities)}</strong><span className="text-xs text-white/70">Activities</span></div><div className="rounded-xl bg-white/10 p-3"><strong className="block text-xl">{draft?.packing.length||0}</strong><span className="text-xs text-white/70">Packing items</span></div></div><p className="mt-6 flex items-start gap-2 text-xs leading-5 text-white/70"><LockKeyhole size={14} className="mt-1 shrink-0"/>Not saved yet. You’ll create a private trip only after reviewing your plan.</p></aside>
      </div>
    </main>
  </div>
}
