import { LanguageRegionSettings } from '../features/locale/LanguageRegionSettings'
import { Link, NavLink, Navigate, useLocation, useParams, useSearchParams } from 'react-router-dom'
import { getSession } from '../features/auth/session'
import { ThemeSettings } from '../features/theme/ThemeToggle'
import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, Bell, Check, ChevronRight, Languages, LockKeyhole, Save, Shield, SlidersHorizontal, Trash2, UserRound } from 'lucide-react'
import { AppShell } from '../layouts/AppShell'
import { Button } from '../components/ui/Button'
import { useSettings } from '../hooks/useSettings'

const sections = [{ id: 'language', label: 'Language & region', icon: Languages }, { id: 'profile', label: 'Profile', icon: UserRound }, { id: 'preferences', label: 'Travel preferences', icon: SlidersHorizontal }, { id: 'notifications', label: 'Notifications', icon: Bell }, { id: 'privacy', label: 'Privacy & security', icon: Shield }]
export function SettingsPage() {
  const { settings, update } = useSettings()
  const { section: routeSection } = useParams()
  const [params] = useSearchParams()
  const location = useLocation()
  const section = routeSection || params.get('section') || ''
  const active = sections.find(item => item.id === section)
  const heading = useRef<HTMLHeadingElement>(null)
  const [saved, setSaved] = useState(false)
  const [privacyAction, setPrivacyAction] = useState<'password' | 'sessions' | null>(null)
  const [notice, setNotice] = useState('')
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'instant' })
    heading.current?.focus({ preventScroll: true })
    setSaved(false); setPrivacyAction(null); setNotice('')
    document.title = `${active?.label || 'Settings'} · Travel Weather`
  }, [location.pathname, active?.label])
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 1800) }
  if (section && !active) return <Navigate to="/app/settings" replace />
  if (!routeSection && active) return <Navigate to={`/app/settings/${active.id}`} replace />
  return <AppShell><main className="settings-page mx-auto max-w-6xl px-5 pb-28 pt-8 md:px-8 lg:px-10 lg:pb-16 lg:pt-10">
    {active && <Link to="/app/settings" className="mb-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-forest"><ArrowLeft size={16} />Back to Settings</Link>}
    <div><p className="eyebrow">{active ? 'Settings' : 'Your account'}</p><h1 ref={heading} tabIndex={-1} className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">{active?.label || 'Settings'}</h1><p className="mt-3 text-sm text-slate">{active ? `Manage your ${active.label.toLowerCase()} preferences.` : 'Choose a category to manage your account and travel preferences.'}</p></div>
    {!active ? <nav className="mt-8 grid gap-3 sm:grid-cols-2" aria-label="Settings categories">{sections.map(({id,label,icon:Icon}) => <Link to={`/app/settings/${id}`} key={id} className="group flex min-h-[100px] items-center gap-4 rounded-2xl border border-black/10 bg-white p-5 transition hover:border-forest/40 hover:shadow-card"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-cream text-forest"><Icon size={21}/></span><span className="min-w-0 flex-1"><span className="block font-semibold">{label}</span><span className="mt-1 block text-xs leading-5 text-slate">{({language:'AI response language and regional formats',profile:'Your profile and appearance',preferences:'Units and travel pace',notifications:'Notification preferences',privacy:'Security options and account controls'} as Record<string,string>)[id]}</span></span><ChevronRight size={18} className="shrink-0 text-slate"/></Link>)}</nav> : <div className="mt-8 grid items-start gap-6 md:grid-cols-[220px_minmax(0,1fr)]">
      <nav className="hidden self-start rounded-2xl border border-black/8 bg-white p-2 md:block" aria-label="Settings categories">{sections.map(({ id, label, icon: Icon }) => <NavLink key={id} to={`/app/settings/${id}`} className={({isActive})=>`flex min-h-12 w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold ${isActive ? 'bg-forest text-white' : 'text-slate hover:bg-black/5 hover:text-ink'}`}><Icon size={17} className="shrink-0" />{label}<ChevronRight size={14} className="ml-auto shrink-0" /></NavLink>)}</nav>
      <section className="rounded-2xl border border-black/8 bg-white p-6 md:p-8">{section !== 'language' && <ThemeSettings />}{section === 'language' && <LanguageRegionSettings />}{section === 'profile' && <div><Header title="Profile" copy="The details used to personalize your travel workspace." /><div className="mt-7 flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-full bg-forest text-2xl font-bold text-white">{settings.displayName.charAt(0).toUpperCase()}</span><div><p className="font-semibold">Profile photo</p><span className="mt-1 block text-xs font-semibold text-slate">Photo upload is available for verified accounts.</span></div></div><label className="mt-8 block max-w-lg"><span className="form-label">Display name</span><input value={settings.displayName} onChange={event => update('displayName', event.target.value)} className="form-input" /></label><label className="mt-5 block max-w-lg"><span className="form-label">Email address</span><input value={getSession()?.user.email || ''} readOnly className="form-input text-slate" /><span className="mt-1 block text-[10px] text-slate">Signed-in account email. Profile preferences currently stay on this device.</span></label></div>}
        {section === 'preferences' && <div><Header title="Travel preferences" copy="These defaults shape recommendations, scores, and packing advice." /><fieldset className="mt-8"><legend className="form-label">Temperature</legend><Segment value={settings.temperatureUnit} options={[['C','Celsius (°C)'],['F','Fahrenheit (°F)']]} onChange={value => update('temperatureUnit', value as 'C' | 'F')} /></fieldset><fieldset className="mt-7"><legend className="form-label">Distance and wind</legend><Segment value={settings.distanceUnit} options={[['km','Kilometers'],['mi','Miles']]} onChange={value => update('distanceUnit', value as 'km' | 'mi')} /></fieldset><fieldset className="mt-7"><legend className="form-label">Default travel pace</legend><Segment value={settings.travelPace} options={[['relaxed','Relaxed'],['balanced','Balanced'],['active','Active']]} onChange={value => update('travelPace', value as 'relaxed' | 'balanced' | 'active')} /></fieldset></div>}
        {section === 'notifications' && <div><Header title="Notifications" copy="Choose which forecast changes should interrupt you." /><div className="mt-7 divide-y divide-black/8">{[{ key: 'emailAlerts' as const, title: 'Email updates', copy: 'Trip summaries and material forecast changes.' }, { key: 'pushAlerts' as const, title: 'Push notifications', copy: 'Time-sensitive weather and itinerary alerts.' }, { key: 'severeWeatherOnly' as const, title: 'Severe weather only', copy: 'Mute routine updates and receive critical conditions only.' }].map(item => <div key={item.key} className="flex items-center gap-5 py-5"><div className="flex-1"><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-slate">{item.copy}</p></div><Toggle checked={settings[item.key]} onChange={value => update(item.key, value)} /></div>)}</div></div>}
        {section === 'privacy' && <div><Header title="Privacy & security" copy="Manage security and control your stored travel data." />{notice && <div role="status" className="mt-5 rounded-xl bg-green-50 p-3 text-sm font-semibold text-green-800">{notice}</div>}<div className="mt-7 space-y-3"><button onClick={() => setPrivacyAction(privacyAction === 'password' ? null : 'password')} className="flex w-full items-center gap-3 rounded-xl border border-black/8 p-4 text-left"><LockKeyhole className="text-forest" size={19} /><span className="flex-1"><strong className="block text-sm">Change password</strong><span className="text-xs text-slate">Use a unique password of at least 10 characters.</span></span><ChevronRight size={16} /></button>{privacyAction === 'password' && <div className="grid gap-3 rounded-xl bg-[#f5f3ec] p-4 sm:grid-cols-2"><label><span className="form-label">New password</span><input type="password" placeholder="At least 10 characters" className="form-input bg-white" /></label><label><span className="form-label">Confirm password</span><input type="password" placeholder="Repeat password" className="form-input bg-white" /></label><div className="sm:col-span-2"><Button size="sm" onClick={() => { setNotice('Password changes are not implemented yet. Your password has not been changed.'); setPrivacyAction(null) }}>Update password</Button></div></div>}<button onClick={() => setPrivacyAction(privacyAction === 'sessions' ? null : 'sessions')} className="flex w-full items-center gap-3 rounded-xl border border-black/8 p-4 text-left"><Shield className="text-forest" size={19} /><span className="flex-1"><strong className="block text-sm">Active sessions</strong><span className="text-xs text-slate">Review devices signed in to your account.</span></span><ChevronRight size={16} /></button>{privacyAction === 'sessions' && <div className="flex items-center gap-3 rounded-xl bg-[#f5f3ec] p-4"><span className="h-2.5 w-2.5 rounded-full bg-green-600" /><div className="flex-1"><p className="text-sm font-semibold">Current browser</p><p className="text-xs text-slate">Kigali, Rwanda · Active now</p></div><span className="text-[10px] font-bold uppercase tracking-[.1em] text-green-800">This device</span></div>}</div><div className="mt-10 border-t border-red-200 pt-6"><p className="text-sm font-semibold text-red-800">Danger zone</p><p className="mt-1 text-xs text-slate">Deleting an account permanently removes trips, packing lists, and conversations.</p><Button variant="secondary" onClick={() => setNotice('Account deletion is not implemented yet. No data was deleted.')} className="mt-4 border-red-200 text-red-700 hover:bg-red-50"><Trash2 size={15} />Delete account</Button></div></div>}
        {section !== 'language' && <div className="mt-10 flex items-center justify-end border-t border-black/8 pt-5"><Button onClick={save}>{saved ? <Check size={16} /> : <Save size={16} />}{saved ? 'Saved' : 'Save changes'}</Button></div>}
      </section></div>}
  </main></AppShell>
}
function Header({ title, copy }: { title: string; copy: string }) { return <div><h2 className="text-2xl font-semibold tracking-[-.03em]">{title}</h2><p className="mt-2 text-sm text-slate">{copy}</p></div> }
function Segment({ value, options, onChange }: { value: string; options: string[][]; onChange: (value: string) => void }) { return <div className="mt-2 flex max-w-xl flex-wrap gap-2">{options.map(([id, label]) => <button key={id} onClick={() => onChange(id)} className={`rounded-xl border px-4 py-3 text-sm font-semibold ${value === id ? 'border-forest bg-forest text-white' : 'border-black/10 bg-white hover:border-forest/40'}`}>{label}</button>)}</div> }
function Toggle({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <button role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={`relative h-7 w-12 rounded-full transition ${checked ? 'bg-forest' : 'bg-black/15'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${checked ? 'left-6' : 'left-1'}`} /></button> }
