import { ActionMenu } from '../components/ui/ActionMenu'
import { formatTripDate } from '../features/locale/preferences'
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarDays, ChevronRight, MapPin, MoreHorizontal, Plus, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { AppShell } from '../layouts/AppShell'
import { Button } from '../components/ui/Button'
import { Skeleton } from '../components/ui/Skeleton'
import { api } from '../services/api'

export function TripsPage() {
  const navigate = useNavigate(); const client = useQueryClient(); const [filter, setFilter] = useState<'upcoming' | 'past'>('upcoming')
  const trips = useQuery({ queryKey: ['trips'], queryFn: api.listTrips })
  const remove = useMutation({ mutationFn: api.deleteTrip, onSuccess: () => client.invalidateQueries({ queryKey: ['trips'] }) })
  const visible = trips.data?.filter(trip => filter === 'upcoming' ? new Date(`${trip.return_date}T23:59:59`) >= new Date() : new Date(`${trip.return_date}T23:59:59`) < new Date()) || []
  return <AppShell><main className="mx-auto max-w-6xl px-5 pb-28 pt-8 md:px-8 lg:px-10 lg:pb-16 lg:pt-10"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Your journeys</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Trips</h1><p className="mt-3 text-sm text-slate">Every forecast, plan, and packing list in one place.</p></div><Button size="lg" onClick={() => navigate('/planner')}><Plus size={18} />Plan a trip</Button></div>
    <div className="mt-9 flex border-b border-black/10">{(['upcoming','past'] as const).map(value => <button key={value} onClick={() => setFilter(value)} className={`border-b-2 px-5 py-3 text-sm font-semibold capitalize ${filter === value ? 'border-forest text-forest' : 'border-transparent text-slate'}`}>{value}</button>)}</div>
    <section className="mt-6">{(trips.isError || remove.isError) && <p role="alert" className="mb-5 rounded-xl border border-red-200 p-4 text-sm">{trips.error?.message || remove.error?.message}</p>}{trips.isLoading ? <div className="space-y-4"><Skeleton className="h-40 rounded-2xl" /><Skeleton className="h-40 rounded-2xl" /></div> : visible.length ? <div className="space-y-4">{visible.map(trip => <article key={trip.id} className="group relative flex flex-col gap-5 rounded-2xl border border-black/8 bg-white p-5 transition hover:border-forest/25 hover:shadow-card sm:flex-row sm:items-center"><Link to={`/trip/${trip.id}`} className="absolute inset-0 rounded-2xl" aria-label={`Open ${trip.destination.name} trip`} /><span className="grid h-16 w-16 shrink-0 place-items-center rounded-xl bg-[#eef1e9] text-3xl">{trip.destination.flag}</span><div className="min-w-0 flex-1"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em] text-forest"><MapPin size={12} />{trip.destination.country}</p><h2 className="mt-2 text-2xl font-semibold">{trip.title}</h2>{trip.stops&&trip.stops.length>1&&<p className="mt-2 text-xs text-slate">{trip.stops.length} stops · {trip.stops.map(stop=>stop.destination.name).join(' → ')}</p>}<p className="mt-2 flex items-center gap-2 text-xs text-slate"><CalendarDays size={14} />{formatDate(trip.departure_date)} – {formatDate(trip.return_date)} · <span className="capitalize">{trip.travel_style}</span></p></div><div className="relative z-10 flex items-center gap-2"><span className="rounded-full bg-green-100 px-3 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-green-800">{trip.status}</span><ActionMenu label="Trip options" items={[{label:'Open trip',href:`/trip/${trip.id}`,icon:<ChevronRight size={16}/>},{label:'Delete trip',icon:<Trash2 size={16}/>,danger:true,disabled:remove.isPending,onSelect:()=>{if(window.confirm('Delete this trip and its plans?'))remove.mutate(trip.id)}}]}/><ChevronRight size={18} className="text-slate" /></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-black/15 bg-white px-6 py-16 text-center"><CalendarDays className="mx-auto text-forest" size={32} /><h2 className="mt-5 text-xl font-semibold">{filter === 'upcoming' ? 'No upcoming trips' : 'No past trips yet'}</h2><p className="mt-2 text-sm text-slate">{filter === 'upcoming' ? 'Pick a destination and we’ll plan around the weather.' : 'Completed journeys will appear here.'}</p>{filter === 'upcoming' && <Button className="mt-6" onClick={() => navigate('/planner')}>Plan a trip</Button>}</div>}</section>
  </main></AppShell>
}
function formatDate(value: string) { return formatTripDate(value) }
