import { ActivityLocationPicker } from '../features/routing/ActivityLocationPicker'
import { DayRoutingPanel } from '../features/routing/DayRoutingPanel'
import { JourneyOverview } from '../features/journey/JourneyOverview'
import { TripStopManager } from '../features/journey/TripStopManager'
import { planStops, stopForDate } from '../features/journey/journey'
import { ModernSelect } from '../components/ui/ModernSelect'
import { TripTools } from '../features/sharing/TripTools'
import { useEffect, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useLocation, useParams } from 'react-router-dom'
import { ArrowDown, ArrowUp, Check, LockKeyhole, Plus, Save, Trash2 } from 'lucide-react'
import { AppShell } from '../layouts/AppShell'
import { api } from '../services/api'
import { Button } from '../components/ui/Button'
import { Skeleton } from '../components/ui/Skeleton'
import type { PrivatePlan } from '../types'

export function TripDashboardPage() {
  const { tripId = '' } = useParams()
  const query = useQuery({ queryKey: ['private-plan', tripId], queryFn: () => api.getPlan(tripId), retry: false, gcTime: 0, refetchOnWindowFocus: false })
  return <AppShell><main className="mx-auto max-w-6xl px-5 py-8 pb-28 md:px-8">
    {query.isLoading ? <Skeleton className="h-80 w-full rounded-2xl" /> : query.isError || !query.data ? <section className="rounded-2xl bg-white p-8"><h1 className="text-3xl font-semibold">Trip unavailable</h1><p className="mt-3 text-slate">{query.error?.message || 'This trip does not belong to your account.'}</p><Link to="/app/trips" className="mt-5 inline-block font-semibold text-forest underline">Back to your trips</Link></section> : <PrivateTripEditor key={tripId} initial={query.data} />}
  </main></AppShell>
}
export function PrivateTripEditor({ initial, shareToken, readOnly = false }: { initial: PrivatePlan; shareToken?: string; readOnly?: boolean }) {
  const location = useLocation()
  const queryClient = useQueryClient()
  const [plan, setPlan] = useState(initial)
  const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [dayIndex, setDayIndex] = useState(0)
  const [stopEditing,setStopEditing] = useState(false)
  const stops = planStops(plan)
  const activeStop = stopForDate(stops,plan.itinerary[dayIndex]?.date||plan.departure_date)
  const d = activeStop.destination
  const routingConfig=useQuery({queryKey:['routing-config'],queryFn:api.routingConfig,enabled:!shareToken,staleTime:60000,retry:false})
  const current = useQuery({ queryKey: ['live-current', d.id], queryFn: () => api.getMapWeather(d.latitude, d.longitude), retry: 1, enabled: !shareToken })
  const forecast = useQuery({ queryKey: ['live-forecast', d.id, activeStop.arrival_date], queryFn: () => api.getForecast(d.latitude, d.longitude, activeStop.arrival_date), retry: 1, enabled: !shareToken })
  const weather = current.data?.data
  useEffect(()=>{
    if(shareToken || !['#weather','#itinerary','#directions','#packing'].includes(location.hash))return
    const frame=requestAnimationFrame(()=>{
      const target=document.getElementById(location.hash.slice(1))
      target?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})
      target?.focus({preventScroll:true})
    })
    return()=>cancelAnimationFrame(frame)
  },[location.hash,plan.trip_id,shareToken])
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty || stopEditing) { e.preventDefault(); e.returnValue = '' } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn) }, [dirty, stopEditing])
  function change(next: PrivatePlan) { setPlan(next); setDirty(true); setNotice(''); setError('') }
  async function save() {
    if (plan.itinerary.some(day=>day.items.some(item=>item.duration_minutes!=null&&(!Number.isInteger(item.duration_minutes)||item.duration_minutes<0||item.duration_minutes>1440)))) { setError('Activity durations must be whole minutes from 0 to 1440, or left empty.'); return }
    setSaving(true); setError(''); setNotice('')
    try { const result = shareToken ? await api.saveSharedPlan(shareToken, plan) : await api.savePlan(plan.trip_id, plan); setPlan(value => ({ ...value, revision: result.revision })); if (!shareToken) queryClient.setQueryData(['private-plan', plan.trip_id], { ...plan, revision: result.revision }); setDirty(false); setNotice(shareToken ? 'Changes saved to the shared trip.' : 'All changes saved to your account.') }
    catch (e) { setError(e instanceof Error ? e.message : 'Unable to save. Your changes are still here. Try again.') }
    finally { setSaving(false) }
  }
  const day = plan.itinerary[dayIndex]
  function changeItems(items: PrivatePlan['itinerary'][number]['items']) { change({ ...plan, itinerary: plan.itinerary.map((value, index) => index === dayIndex ? { ...value, items } : value) }) }
  function move(index: number, delta: number) { const items = [...day.items]; const target = index + delta; if (target < 0 || target >= items.length) return; [items[index], items[target]] = [items[target], items[index]]; changeItems(items) }
  return <>
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow flex items-center gap-2"><LockKeyhole size={14} />{shareToken ? (readOnly ? 'Shared trip · View only' : 'Shared trip · Can edit') : 'Private trip'}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{d.flag} {plan.title}</h1><p className="mt-3 text-sm text-slate">{plan.departure_date} – {plan.return_date} · {stops.map(stop=>stop.destination.name).join(' → ')}</p></div>{!readOnly && <Button onClick={save} disabled={!dirty || saving || stopEditing}><Save size={17} />{saving ? 'Saving…' : 'Save all changes'}</Button>}</div>
    {!shareToken&&<nav aria-label="Trip sections" className="trip-section-shortcuts mt-6 grid grid-cols-4 gap-1 rounded-xl border border-black/10 bg-white p-1">{[['weather','Weather'],['itinerary','Itinerary'],['directions','Directions'],['packing','Packing']].map(([id,label])=><Link key={id} to={`#${id}`} aria-current={location.hash===`#${id}`?'location':undefined} className={`flex min-h-12 items-center justify-center rounded-lg px-1 text-xs font-semibold sm:text-sm ${location.hash===`#${id}`?'bg-forest text-white':'text-forest hover:bg-cream'}`}>{label}</Link>)}</nav>}
    <div className="mt-4" aria-live="polite">{dirty && <p className="text-sm text-slate">You have unsaved changes. Save before leaving this page.</p>}{notice && <p className="flex items-center gap-2 text-sm text-forest"><Check size={16} />{notice}</p>}{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error} Your edits have not been discarded.</p>}</div>
    <JourneyOverview stops={stops} activeId={activeStop.id} onSelect={stop=>{const index=plan.itinerary.findIndex(day=>day.date>=stop.arrival_date&&day.date<=stop.departure_date);if(index>=0)setDayIndex(index)}}/>
    {!shareToken&&<TripStopManager plan={plan} disabled={dirty||saving} onEditingChange={setStopEditing} onSaved={value=>{setPlan(value);queryClient.setQueryData(['private-plan',value.trip_id],value);queryClient.invalidateQueries({queryKey:['trips']});setDayIndex(0);setDirty(false);setNotice('Stops saved. Review your activities and local times.')}}/>}
    {!shareToken && <TripTools tripId={plan.trip_id} dirty={dirty || saving || stopEditing} />}
    {!shareToken && <><section id="weather" tabIndex={-1} className="mt-8 rounded-2xl bg-[#173f30] p-6 text-white"><h2 className="text-xl font-semibold">Live destination weather</h2><p className="mt-2 text-sm text-white/80">{d.name}, {d.country} · {activeStop.arrival_date} – {activeStop.departure_date}</p>{current.isLoading ? <Skeleton className="mt-4 h-24 w-full" /> : current.isError ? <p className="mt-3">Live weather is unavailable. You can still edit and save your plan. <button className="underline" onClick={() => current.refetch()}>Retry weather</button></p> : weather && <><p className="mt-5 text-5xl font-light">{weather.temperature} °C</p><p className="mt-2">{weather.condition} · Feels like {weather.feels_like} °C</p><p className="mt-3 text-sm text-white/80">Wind {weather.wind} km/h · Rain probability {weather.precipitation ?? '—'}% · Humidity {weather.humidity}%</p><p className="mt-4 text-xs text-white/80">{current.data?.meta?.provider === 'development_mock' ? 'Development demo data — not live' : 'Open-Meteo · Model-based conditions'} · Data time: {weather.observed_at} {weather.timezone}</p></>}
      <p className="mt-5 border-t border-white/20 pt-4 text-xs leading-5 text-white/80">Current conditions describe the destination now, not your future trip. Forecasts can change. Official severe-weather alerts are not included.</p>
    </section>
    <section className="mt-5 rounded-2xl border border-black/10 bg-white p-5"><h2 className="text-xl font-semibold">Trip forecast</h2>{forecast.isLoading ? <Skeleton className="mt-4 h-32 w-full" /> : forecast.isError ? <p className="mt-3 text-sm text-slate">Forecast unavailable. <button className="underline" onClick={() => forecast.refetch()}>Retry</button></p> : !forecast.data?.length ? <p className="mt-3 text-sm text-slate">Your dates are outside the available forecast window (up to 16 days). Your trip is saved; check back closer to departure.</p> : <><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{forecast.data.filter(value => value.date <= activeStop.departure_date).map(value => <article key={value.date} className="rounded-xl bg-cream p-4"><p className="text-sm font-semibold">{value.date}</p><p className="mt-3 text-2xl">{value.high}° / {value.low}°</p><p className="mt-2 text-xs text-slate">{value.condition} · Rain {value.rain_probability}%</p></article>)}</div><p className="mt-3 text-xs text-slate">Showing only dates covered by the provider, not necessarily your entire trip.</p></>}</section>
    </>}
    <fieldset disabled={saving || readOnly || stopEditing} className="mt-8 space-y-6">
      <section id="itinerary" tabIndex={-1} className="rounded-2xl border border-black/10 bg-white p-5 md:p-7"><h2 className="text-2xl font-semibold">Your itinerary</h2><p className="mt-2 text-sm text-slate">Add activities, edit times, and change their order. Nothing is booked automatically. Times use {d.timezone} for the selected day.</p><div className="mt-4"><label className="form-label">Travel between activities</label><ModernSelect label="Travel between activities" value={day?.travel_mode||'DRIVE'} onValueChange={mode=>change({...plan,itinerary:plan.itinerary.map((value,index)=>index===dayIndex?{...value,travel_mode:mode as 'DRIVE'|'WALK'|'BICYCLE'}:value)})} options={[{value:'DRIVE',label:'Driving',description:'Traffic-unaware estimates'},{value:'WALK',label:'Walking',description:'Coverage may omit sidewalks; use caution'},{value:'BICYCLE',label:'Cycling',description:'Coverage may omit cycleways; use caution'}]} searchable={false}/></div><label className="mt-5 block"><span className="form-label">Trip day</span><ModernSelect label="Trip day" value={String(dayIndex)} onValueChange={value=>setDayIndex(Number(value))} options={plan.itinerary.map((item,index)=>({value:String(index),label:item.date,description:`${stopForDate(stops,item.date).destination.name} · ${item.label}`}))} searchable={plan.itinerary.length>6} searchPlaceholder="Search trip dates…" /></label>
      <div className="mt-5 space-y-3">{day?.items.map((item, index) => <div key={item.id} className="grid gap-3 rounded-xl bg-cream p-3 sm:grid-cols-[110px_1fr_auto]"><input aria-label={`Activity ${index + 1} time`} type="time" className="form-input" value={item.time} onChange={e => changeItems(day.items.map(value => value.id === item.id ? { ...value, time: e.target.value } : value))} /><input dir="auto" aria-label={`Activity ${index + 1} title`} className="form-input" maxLength={180} value={item.title} onChange={e => changeItems(day.items.map(value => value.id === item.id ? { ...value, title: e.target.value } : value))} /><div className="flex gap-1"><button type="button" aria-label="Move activity up" disabled={index === 0} className="p-3 disabled:opacity-30" onClick={() => move(index, -1)}><ArrowUp size={16} /></button><button type="button" aria-label="Move activity down" disabled={index === day.items.length - 1} className="p-3 disabled:opacity-30" onClick={() => move(index, 1)}><ArrowDown size={16} /></button><button type="button" aria-label="Remove activity" className="p-3" onClick={() => changeItems(day.items.filter(value => value.id !== item.id))}><Trash2 size={16} /></button></div><div className="grid gap-3 sm:col-span-3 sm:grid-cols-[150px_minmax(0,1fr)]"><label><span className="form-label">Duration (minutes)</span><input aria-label={`Activity ${index+1} duration`} type="number" min={0} max={1440} className="form-input" placeholder="Not set" value={item.duration_minutes??''} onChange={e=>changeItems(day.items.map(value=>value.id===item.id?{...value,duration_minutes:e.target.value===''?null:Number(e.target.value)}:value))}/></label>{!shareToken?<ActivityLocationPicker tripId={plan.trip_id} dayDate={day.date} enabled={!!routingConfig.data?.places_available} value={item.location} onChange={location=>changeItems(day.items.map(value=>value.id===item.id?{...value,location}:value))}/>:<p className="self-end text-xs text-slate">{item.location?'Google place linked. The owner manages location search.':'Location not linked. Ask the owner to add a place.'}</p>}</div></div>)}</div>
      {!day?.items.length && <p className="my-5 text-sm text-slate">No activities yet. Start with one thing you want to do.</p>}<Button variant="secondary" className="mt-4" disabled={!day} onClick={() => changeItems([...day.items, { id: crypto.randomUUID(), time: '09:00', title: 'New activity', category: 'custom' }])}><Plus size={16} />Add activity</Button></section>
      <section id="packing" tabIndex={-1} className="rounded-2xl border border-black/10 bg-white p-5 md:p-7"><h2 className="text-2xl font-semibold">Packing list</h2><p className="mt-2 text-sm text-slate">{plan.packing.filter(item => item.packed).length} of {plan.packing.length} packed · Personalize these essentials for your journey.</p><div className="mt-5 space-y-3">{plan.packing.map((item, index) => <div key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-cream p-3"><input type="checkbox" aria-label={`Packed ${item.name}`} checked={item.packed} onChange={e => change({ ...plan, packing: plan.packing.map(value => value.id === item.id ? { ...value, packed: e.target.checked } : value) })} className="h-6 w-6 accent-emerald-700" /><input className="form-input min-w-0 flex-1" style={{ minWidth: 120 }} dir="auto" aria-label={`Packing item ${index + 1} name`} value={item.name} maxLength={180} onChange={e => change({ ...plan, packing: plan.packing.map(value => value.id === item.id ? { ...value, name: e.target.value } : value) })} /><input type="number" min={1} max={99} aria-label={`Quantity for ${item.name}`} className="form-input !w-20" value={item.quantity} onChange={e => change({ ...plan, packing: plan.packing.map(value => value.id === item.id ? { ...value, quantity: Number(e.target.value) } : value) })} /><button type="button" aria-label={`Remove ${item.name}`} className="p-3" onClick={() => change({ ...plan, packing: plan.packing.filter(value => value.id !== item.id) })}><Trash2 size={16} /></button></div>)}</div><Button className="mt-4" variant="secondary" onClick={() => change({ ...plan, packing: [...plan.packing, { id: crypto.randomUUID(), name: 'New item', quantity: 1, packed: false, category: 'My essentials' }] })}><Plus size={16} />Add packing item</Button></section>
    </fieldset>
    {!shareToken&&<DayRoutingPanel plan={plan} dayIndex={dayIndex} dirty={dirty||saving||stopEditing} config={routingConfig.data} onDayChange={setDayIndex} onSave={save} saveDisabled={saving||stopEditing}/>}
    <div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-xs text-slate">{shareToken ? (readOnly ? 'View-only link. Ask the owner for editing access.' : 'You can edit the itinerary and packing list, but not manage the trip or its sharing links.') : 'Private to your account and anyone holding an active sharing link.'}</p>{!readOnly && <Button onClick={save} disabled={!dirty || saving || stopEditing}><Save size={16} />{saving ? 'Saving…' : 'Save all changes'}</Button>}</div>
  </>
}
