import { ArrowDown, ArrowUp, MapPin, Plus, Trash2 } from 'lucide-react'
import { DestinationSearch } from '../destinations/DestinationSearch'
import { Button } from '../../components/ui/Button'
import { addDays, dayCount, validateJourney, type DraftStop } from './journey'

export function StopEditor({stops,onChange,minDate}:{stops:DraftStop[];onChange:(stops:DraftStop[])=>void;minDate?:string}){
  const errors=validateJourney(stops,minDate)
  const update=(index:number,change:Partial<DraftStop>)=>onChange(stops.map((stop,i)=>i===index?{...stop,...change}:stop))
  const canReorder=stops.every(stop=>Number.isFinite(dayCount(stop.arrival_date,stop.departure_date))&&dayCount(stop.arrival_date,stop.departure_date)>0)
  function move(index:number,delta:number){const next=[...stops];[next[index],next[index+delta]]=[next[index+delta],next[index]];let cursor=stops[0].arrival_date;onChange(next.map(stop=>{const duration=dayCount(stop.arrival_date,stop.departure_date);const result={...stop,arrival_date:cursor,departure_date:addDays(cursor,duration-1)};cursor=addDays(cursor,duration);return result}))}
  return <div className="space-y-4"><p className="text-xs leading-5 text-slate">Add stops in travel order. Arrival and last day are inclusive: each calendar day belongs to one stop. Put transfers on the arriving stop’s first day. This schedule does not calculate routes or travel times.</p>
    {stops.map((stop,index)=><section key={stop.key} className="rounded-2xl border border-black/10 bg-cream p-4" aria-label={`Stop ${index+1}`}><div className="mb-4 flex items-center justify-between gap-3"><h3 className="flex items-center gap-2 text-sm font-semibold"><span className="grid h-7 w-7 place-items-center rounded-full bg-forest text-xs text-white">{index+1}</span>{stop.destination?.name||'Choose a destination'}</h3><div className="flex gap-1">{stops.length>1&&<><button type="button" className="grid h-10 w-10 place-items-center rounded-lg disabled:opacity-30" disabled={!canReorder||index===0} aria-label={`Move stop ${index+1} earlier`} onClick={()=>move(index,-1)}><ArrowUp size={16}/></button><button type="button" className="grid h-10 w-10 place-items-center rounded-lg disabled:opacity-30" disabled={!canReorder||index===stops.length-1} aria-label={`Move stop ${index+1} later`} onClick={()=>move(index,1)}><ArrowDown size={16}/></button><button type="button" className="grid h-10 w-10 place-items-center rounded-lg" aria-label={`Remove stop ${index+1}`} onClick={()=>onChange(stops.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></>}</div></div>
      <DestinationSearch value={stop.destination} onSelect={destination=>update(index,{destination})} onClear={()=>update(index,{destination:null})}/>
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><label htmlFor={`${stop.key}-arrival`}><span className="form-label">Arrival</span><input id={`${stop.key}-arrival`} aria-label={`Stop ${index+1} arrival`} type="date" value={stop.arrival_date} min={minDate} className="form-input" onChange={e=>update(index,{arrival_date:e.target.value})}/></label><label htmlFor={`${stop.key}-last`}><span className="form-label">Last day here</span><input id={`${stop.key}-last`} aria-label={`Stop ${index+1} last day`} type="date" min={stop.arrival_date} value={stop.departure_date} className="form-input" onChange={e=>update(index,{departure_date:e.target.value})}/></label></div>
      {stop.destination&&<p className="mt-3 flex items-center gap-2 text-xs text-slate"><MapPin size={13}/>{stop.destination.country} · {stop.destination.timezone}</p>}
    </section>)}
    <Button type="button" variant="secondary" disabled={stops.length>=12||!stops.at(-1)?.departure_date||!Number.isFinite(Date.parse(stops.at(-1)!.departure_date))} onClick={()=>{const arrival=addDays(stops.at(-1)!.departure_date,1);onChange([...stops,{key:crypto.randomUUID(),destination:null,arrival_date:arrival,departure_date:addDays(arrival,1)}])}}><Plus size={16}/>Add another stop</Button>
    {stops.length>1&&<p className="text-xs leading-5 text-slate">Reordering keeps each visit’s length and reschedules stops from your original departure date. Removing a stop leaves its dates for you to reassign.</p>}
    {!!errors.length&&<ul className="space-y-1 rounded-xl border border-amber/40 bg-white p-3 text-xs leading-5 text-slate" aria-label="Stop schedule checks" aria-live="polite">{errors.map(error=><li key={error}>{error}</li>)}</ul>}
  </div>
}
