import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Bot, CornerDownLeft, MessageCircle, Sparkles, X } from 'lucide-react'
import { useMutation } from '@tanstack/react-query'
import { api } from '../../services/api'

const prompts = ['What should I wear tomorrow?', 'Should I carry an umbrella?', 'Which day has the best weather?']
type Message = { role: 'assistant' | 'user'; text: string; sources?: string[] }
export function TravelAssistant({ tripId }: { tripId: string }) {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', text: 'Hi Jallah — I can help with this trip using the forecast, your activities, and itinerary. What would you like to know?' }])
  const chat = useMutation({ mutationFn: (message: string) => api.chat(tripId, message), onSuccess: data => setMessages(v => [...v, { role: 'assistant', text: data.answer, sources: data.grounded_in }]), onError: () => setMessages(v => [...v, { role: 'assistant', text: 'I couldn’t reach travel intelligence just now. Please try again.' }]) })
  const send = (value = input) => { if (!value.trim() || chat.isPending) return; setMessages(v => [...v, { role: 'user', text: value }]); setInput(''); chat.mutate(value) }
  return <><button onClick={() => setOpen(true)} className="fixed bottom-20 right-5 z-30 flex h-12 items-center gap-2 rounded-full bg-amber px-4 text-sm font-bold text-ink shadow-xl transition hover:-translate-y-1 lg:bottom-7 lg:right-8" aria-label="Ask Travel AI"><Sparkles size={17} /> <span className="hidden sm:inline">Ask Travel AI</span></button>
    <AnimatePresence>{open && <motion.aside initial={{ opacity: 0, y: 20, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 12, scale: .98 }} className="fixed inset-x-3 bottom-3 z-50 flex h-[min(680px,calc(100vh-24px))] flex-col overflow-hidden rounded-2xl border border-black/10 bg-[#f8f7f2] shadow-2xl sm:left-auto sm:right-5 sm:w-[420px]">
      <header className="flex items-center gap-3 bg-[#173f30] p-4 text-white"><span className="grid h-9 w-9 place-items-center rounded-full bg-amber text-ink"><Bot size={18} /></span><div className="flex-1"><h2 className="text-sm font-semibold">Travel AI</h2><p className="text-[10px] text-white/50">Grounded in your live trip data</p></div><button onClick={() => setOpen(false)} className="grid h-8 w-8 place-items-center rounded-full hover:bg-white/10" aria-label="Close assistant"><X size={18} /></button></header>
      <div className="flex-1 space-y-4 overflow-y-auto p-4">{messages.map((message, i) => <div key={i} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[86%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.role === 'user' ? 'rounded-br-sm bg-forest text-white' : 'rounded-bl-sm border border-black/8 bg-white text-ink'}`}><p>{message.text}</p>{message.sources && <div className="mt-2 border-t border-black/8 pt-2 text-[9px] font-bold uppercase tracking-[.1em] text-slate">Based on · {message.sources.join(' · ')}</div>}</div></div>)}{chat.isPending && <div className="flex gap-1 px-4"><span className="h-2 w-2 animate-bounce rounded-full bg-forest/40" /><span className="h-2 w-2 animate-bounce rounded-full bg-forest/40 [animation-delay:120ms]" /><span className="h-2 w-2 animate-bounce rounded-full bg-forest/40 [animation-delay:240ms]" /></div>}</div>
      {messages.length < 3 && <div className="no-scrollbar flex gap-2 overflow-x-auto px-4 pb-3">{prompts.map(p => <button key={p} onClick={() => send(p)} className="shrink-0 rounded-full border border-black/10 bg-white px-3 py-1.5 text-[11px] font-semibold text-slate hover:border-forest hover:text-forest">{p}</button>)}</div>}
      <div className="border-t border-black/8 bg-white p-3"><div className="flex items-end gap-2 rounded-xl bg-[#f1efe7] p-2"><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send() } }} rows={1} placeholder="Ask about weather, packing, or plans…" className="max-h-24 min-h-9 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none" /><button onClick={() => send()} className="grid h-9 w-9 place-items-center rounded-lg bg-forest text-white" aria-label="Send"><CornerDownLeft size={16} /></button></div><p className="mt-2 text-center text-[9px] text-slate">Weather guidance is probabilistic. Verify severe-weather alerts locally.</p></div>
    </motion.aside>}</AnimatePresence></>
}
