import { test, expect } from '@playwright/test'

test('modern picker filters, selects, restores focus and supports both themes', async ({ page }) => {
  await page.addInitScript(() => {
    sessionStorage.setItem('travel-weather-session', JSON.stringify({ user: { email: 'test@example.com' }, access_token: 'test-only', expiresAt: Date.now() + 600000 }))
    localStorage.setItem('travel-weather:theme', 'dark')
  })
  await page.route('**/api/v1/destinations/search?*', route => route.fulfill({ json: { success: true, data: [
    { id: 'ng', name: 'Nigeria', country: 'Nigeria', country_code: 'NG', flag: '🇳🇬', latitude: 9.08, longitude: 8.67, timezone: 'Africa/Lagos' },
    { id: 'rw', name: 'Kigali', country: 'Rwanda', country_code: 'RW', flag: '🇷🇼', latitude: -1.9441, longitude: 30.0619, timezone: 'Africa/Kigali' },
  ] } }))
  await page.goto('/app/weather-map')
  const trigger = page.getByRole('button', { name: /Find a destination/ })
  await trigger.click()
  const filter = page.getByRole('combobox', { name: 'Filter destinations' })
  await expect(filter).toBeFocused()
  await filter.fill('Nigeria')
  await expect(page.getByRole('option')).toHaveCount(1)
  await filter.press('Enter')
  await expect(trigger).toContainText('Nigeria')
  await expect(trigger).toContainText('Country')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(page.getByRole('option', { name: /Nigeria/ })).toHaveAttribute('aria-selected', 'true')
  await filter.fill('zzzz')
  await expect(page.getByText('No matches found')).toBeVisible()
  await page.getByRole('button', { name: 'Clear search' }).click()
  await filter.press('Escape')
  await expect(trigger).toBeFocused()
  await page.getByRole('button', { name: 'Switch to light mode' }).click()
  await trigger.click()
  await expect(filter).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('dropdown does not resize, unmount or scroll away the map', async ({ page }) => {
  await page.addInitScript(() => sessionStorage.setItem('travel-weather-session', JSON.stringify({ user: { email: 'layout@example.com' }, access_token: 'test-only', expiresAt: Date.now() + 600000 })))
  await page.route('**/api/v1/destinations/search?*', route => route.fulfill({ json: { success: true, data: Array.from({ length: 16 }, (_, i) => ({ id: `location-${i}`, name: `Test location ${i}`, country: 'Rwanda', flag: '🇷🇼', latitude: -1.94, longitude: 30.06, timezone: 'Africa/Kigali' })) } }))
  await page.goto('/app/weather-map')
  const map = page.getByRole('region', { name: 'Interactive geographic map' })
  await expect(page.locator('.maplibregl-canvas')).toBeVisible()
  const trigger = page.getByRole('button', { name: /Find a destination/ })
  await trigger.scrollIntoViewIfNeeded()
  const before = await map.boundingBox()
  const scrollBefore = await page.evaluate(() => scrollY)
  await trigger.click()
  const filter = page.getByRole('combobox', { name: 'Filter destinations' })
  await filter.press('Control+End')
  const after = await map.boundingBox()
  expect(after?.width).toBe(before?.width)
  expect(after?.height).toBe((page.viewportSize()?.width || 1280) < 640 ? 440 : 600)
  expect(await page.evaluate(() => scrollY)).toBe(scrollBefore)
  await filter.press('Enter')
  await expect(page.locator('.maplibregl-canvas')).toHaveCount(1)
  const selected = await map.boundingBox()
  expect(selected?.width).toBe(before?.width)
  expect(selected?.height).toBe(before?.height)
  expect(await page.evaluate(() => scrollY)).toBe(scrollBefore)
})
