import { expect, test } from '@playwright/test'

test('theme toggle persists across public pages and reloads', async ({ page }) => {
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Switch to dark mode' }).click()
  await expect(page.locator('html')).toHaveClass('dark')
  await page.getByRole('link', { name: 'Log in', exact: true }).click()
  await expect(page.locator('html')).toHaveClass('dark')
  await expect(page.locator('main')).toHaveCSS('background-color', 'rgb(16, 25, 20)')
  await expect(page.locator('main')).toHaveCSS('color', 'rgb(234, 239, 233)')
  await expect(page.getByLabel('Email address')).toHaveCSS('background-color', 'rgb(21, 34, 27)')
  await page.reload()
  await expect(page.locator('html')).toHaveClass('dark')
  await page.getByRole('link', { name: 'Create an account' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Switch to light mode' }).click()
  await expect(page.locator('html')).not.toHaveClass('dark')
  await page.reload()
  await expect(page.locator('html')).not.toHaveClass('dark')
})

test('system preference and workspace appearance controls stay in sync', async ({ page, request }) => {
  await page.emulateMedia({ colorScheme: 'dark' })
  const response = await request.post('/api/v1/auth/register', { data: { display_name: 'Theme Tester', email: `theme-${Date.now()}-${Math.random().toString(36).slice(2)}@example.com`, password: 'Theme-test-password-42' } })
  const { data } = await response.json()
  await page.addInitScript(session => sessionStorage.setItem('travel-weather-session', JSON.stringify(session)), { ...data, expiresAt: Date.now() + data.expires_in * 1000 })
  await page.goto('/app/settings/profile')
  await expect(page.locator('html')).toHaveClass('dark')
  await expect(page.getByRole('radio', { name: 'System' })).toBeChecked()
  await page.getByRole('radio', { name: 'Light', exact: true }).check()
  await expect(page.locator('html')).not.toHaveClass('dark')
  await page.getByRole('button', { name: 'Switch to dark mode' }).click()
  await expect(page.getByRole('radio', { name: 'Dark', exact: true })).toBeChecked()
  await page.getByRole('radio', { name: 'System' }).check()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).not.toHaveClass('dark')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveClass('dark')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
